# Generated by Django 5.1.3 on 2024-11-28 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_moneda_pais_remove_transaction_is_income_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('ciudad', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('moneda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.moneda')),
                ('pais', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.pais')),
            ],
        ),
    ]
